### ISSUE TITLE
Cambiar la forma en como se guardan las imágenes desde el punto de venta.

### ISSUE THREAD

**Issue by luiscarrillo90** [rols-mart/JSMiMWeb#7]
Tengo una variable 
var host="";
para concatenarle la ruta relativa de la imagen de la mascota y mostrarla en Ver mascota. Debería ser más o menos así:
ver host = "http://www.jsimpresosydisenos.com/"
<img src =host+rutaRelativaDelaImagen>

**Comment by rols-mart** [comment]
Te refieres a la imagen de la mascota o al QR?

**Comment by luiscarrillo90** [comment]
A la imagen de la mascota, el Qr en el host es irrelevante por que está local y es como se utiliza en el sistema

**Comment by rols-mart** [comment]
Ya lo habia cambiado. Lle deje para que guardara solo el nombre de la imagen en la base de datos.

**Comment by rols-mart** [comment]
Lo que acabo de ver es que al parecer Alana registro a su mascota, para hacer pruebas supongo y no guarda bien el nmbre de la imagen cuando es una por default

**Comment by luiscarrillo90** [comment]
Si ya vi, toda la ruta completa guarda

**Comment by rols-mart** [comment]
Listo. En [este commit](https://github.com/rols-mart/jsimpresos/commit/19f2df18b58658643ec5eeb345d3adaf31bd019e)
