### ISSUE TITLE
Cambiar la ruta con la que se crean los códigos qr

### ISSUE THREAD

**Issue by luiscarrillo90** [rols-mart/JSMiMWeb#8]
Al principio era: www.jsimpresosydisenos.com/mascota.php?m=12
ahora debería ser: www.jsimpresosydisenos.com/mascota.html?m=12
por que la página es HTML y no PHP

**Comment by rols-mart** [comment]
De hecho debería ser
 www.mimascota.jsimpresosydisenos.com/mascota.html?m=12

O

mimascota.jsimpresosydisenos.com/mascota.html?m=12

**Comment by rols-mart** [comment]
definitivamente debería ser:

"mimascota.jsimpresosydisenos.com/mascota.html?m="

**Comment by luiscarrillo90** [comment]
Opino lo mismo, entonces mascota.html debe estar en la carpeta del subdominio

**Comment by rols-mart** [comment]
Listo. En [este commit](https://github.com/rols-mart/jsimpresos/commit/549e7b963edca1343485890e7b242c4098ec8264)

**Comment by rols-mart** [comment]
Chingado, le deje php... te digo

**Comment by rols-mart** [comment]
Ahora si, listo. En [este commit](https://github.com/rols-mart/jsimpresos/commit/6c66fe5d8c436ab66e693f5951846690a1768caf)
